"""Initial migration with pgvector

Revision ID: 59f421faacce
Revises: 
Create Date: 2026-03-26 13:58:00.978344+09:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector.sqlalchemy.vector

# revision identifiers, used by Alembic.
revision: str = '59f421faacce'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """アップグレード処理"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False, comment='Title'),
    sa.Column('summary', sa.Text(), nullable=True, comment='Summary'),
    sa.Column('content', sa.Text(), nullable=True, comment='Full text'),
    sa.Column('original_url', sa.String(length=1000), nullable=True, comment='Original URL'),
    sa.Column('source', sa.String(length=100), nullable=False, comment='Source'),
    sa.Column('category', sa.String(length=50), nullable=True, comment='Category'),
    sa.Column('tags', postgresql.ARRAY(sa.Text()), nullable=True, comment='Tags'),
    sa.Column('published_at', sa.DateTime(), nullable=True, comment='Published at'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='Created at'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='Updated at'),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True, comment='Vector embedding'),
    sa.Column('content_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Metadata'),
    sa.Column('view_count', sa.Integer(), nullable=True, comment='View count'),
    sa.Column('like_count', sa.Integer(), nullable=True, comment='Like count'),
    sa.Column('is_processed', sa.Boolean(), nullable=True, comment='Processed flag'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('original_url')
    )
    op.create_index(op.f('ix_contents_id'), 'contents', ['id'], unique=False)
    op.create_table('entities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False, comment='Entity name'),
    sa.Column('type', sa.String(length=50), nullable=False, comment='Type(model, company, person, technology)'),
    sa.Column('description', sa.Text(), nullable=True, comment='Description'),
    sa.Column('aliases', postgresql.ARRAY(sa.Text()), nullable=True, comment='Aliases'),
    sa.Column('entity_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Metadata'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='Created at'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='Updated at'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_entities_id'), 'entities', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False, comment='Email address'),
    sa.Column('password_hash', sa.String(length=255), nullable=False, comment='Password hash'),
    sa.Column('preferences', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='User preferences'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='Active flag'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='Created at'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='Updated at'),
    sa.Column('last_login_at', sa.DateTime(), nullable=True, comment='Last login at'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('api_keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='User ID'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='Key name'),
    sa.Column('key_hash', sa.String(length=255), nullable=False, comment='Key hash'),
    sa.Column('key_prefix', sa.String(length=20), nullable=True, comment='Key prefix'),
    sa.Column('rate_limit', sa.Integer(), nullable=True, comment='Rate limit'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='Active flag'),
    sa.Column('last_used_at', sa.DateTime(), nullable=True, comment='Last used at'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='Created at'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key_hash')
    )
    op.create_index(op.f('ix_api_keys_id'), 'api_keys', ['id'], unique=False)
    op.create_table('entity_relations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_entity_id', sa.Integer(), nullable=False, comment='Source entity ID'),
    sa.Column('target_entity_id', sa.Integer(), nullable=False, comment='Target entity ID'),
    sa.Column('relation_type', sa.String(length=100), nullable=False, comment='Relation type'),
    sa.Column('weight', sa.Float(), nullable=True, comment='Weight'),
    sa.Column('evidence', sa.Text(), nullable=True, comment='Evidence'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='Created at'),
    sa.ForeignKeyConstraint(['source_entity_id'], ['entities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_entity_id'], ['entities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entity_relations_id'), 'entity_relations', ['id'], unique=False)
    op.create_table('user_actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='User ID'),
    sa.Column('content_id', sa.Integer(), nullable=False, comment='Content ID'),
    sa.Column('action_type', sa.String(length=20), nullable=False, comment='Action type(view, like, bookmark, share)'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='Created at'),
    sa.Column('action_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Metadata'),
    sa.ForeignKeyConstraint(['content_id'], ['contents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_actions_id'), 'user_actions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """ダウングレード処理"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_actions_id'), table_name='user_actions')
    op.drop_table('user_actions')
    op.drop_index(op.f('ix_entity_relations_id'), table_name='entity_relations')
    op.drop_table('entity_relations')
    op.drop_index(op.f('ix_api_keys_id'), table_name='api_keys')
    op.drop_table('api_keys')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_entities_id'), table_name='entities')
    op.drop_table('entities')
    op.drop_index(op.f('ix_contents_id'), table_name='contents')
    op.drop_table('contents')
    # ### end Alembic commands ###
